# Generated by Django 5.1.4 on 2025-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
